export { default as Home } from "./Home"
export { default as NotFound } from "./NotFound"
export { default as Product } from "./Product"
export { default as Cart } from "./Cart"
export { default as Marketing } from "./Marketing"
export { default as ProductDetailPage } from "./ProductDetailPage"
export { default as Wishlist } from "./Wishlist"
